Grades = int(input('add ur grades everything u have and divide it by amount of it'))
grade1 = int(input())
grade2 = int(input())
grade3 = int(input())
print(Grades + ((grade1 + grade2 + grade3) // 3) )